apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql{{ .Values.env_hyp }}
  labels:
    app: graphql{{ .Values.env_hyp }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql{{ .Values.env_hyp }}
  template:
    metadata:
      labels:
        app: graphql{{ .Values.env_hyp }}
    spec:
      containers:
      - name: graphql{{ .Values.env_hyp }}
        image: abhinavmedikonda/graphql:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: ACCOUNT_SERVICE_URL
          value: "account{{ .Values.env_hyp }}:80"
        - name: CATALOG_SERVICE_URL
          value: "catalog{{ .Values.env_hyp }}:80"
        - name: ORDER_SERVICE_URL
          value: "order{{ .Values.env_hyp }}:80"
