apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: graphql-{{ .Values.env }}
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: abhinavmedikonda/oms-graphql-api:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: ACCOUNT_SERVICE_URL
          value: "api.account-{{ .Values.env }}:80"
        - name: CATALOG_SERVICE_URL
          value: "api.catalog-{{ .Values.env }}:80"
        - name: ORDER_SERVICE_URL
          value: "api.order-{{ .Values.env }}:80"
