apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: graphql-{{ .Values.env }}
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "oms{{- if and .Values.env (ne .Values.env \"prod\") -}}-{{ .Values.env }}{{- end }}.local"
    http:
      paths:
      - pathType: Prefix
        path: "/graphql"
        backend:
          service:
            name: api
            port:
              number: 80
      - pathType: Prefix
        path: "/playground"
        backend:
          service:
            name: api
            port:
              number: 80
