apiVersion: v1
kind: Service
metadata:
  name: graphql{{ .Values.env_hyp }}
  labels:
    app: graphql{{ .Values.env_hyp }}
spec:
  selector:
    app: graphql{{ .Values.env_hyp }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
