apiVersion: v1
kind: Namespace
metadata:
  name: account-{{ .Values.env }}
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: account
  namespace: account-{{ .Values.env }}
spec:
  mtls:
    mode: STRICT
---
apiVersion: v1
kind: Namespace
metadata:
  name: catalog-{{ .Values.env }}
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: catalog
  namespace: catalog-{{ .Values.env }}
spec:
  mtls:
    mode: STRICT
---
apiVersion: v1
kind: Namespace
metadata:
  name: order-{{ .Values.env }}
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: order
  namespace: order-{{ .Values.env }}
spec:
  mtls:
    mode: STRICT
---
apiVersion: v1
kind: Namespace
metadata:
  name: graphql-{{ .Values.env }}
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: graphql
  namespace: graphql-{{ .Values.env }}
spec:
  mtls:
    mode: PERMISSIVE