apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: account{{ .Values.env_hyp }}
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: abhinavmedikonda/account:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgres://abhi:1234@db.account{{ .Values.env_hyp }}:5432/account_db{{ .Values.env_und }}?sslmode=disable"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: account{{ .Values.env_hyp }}
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: abhinavmedikonda/account-db:v1
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "account_db{{ .Values.env_und }}"
        - name: POSTGRES_USER
          value: "abhi"
        - name: POSTGRES_PASSWORD
          value: "1234"
