apiVersion: apps/v1
kind: Deployment
metadata:
  name: account{{ .Values.env_hyp }}
  labels:
    app: account{{ .Values.env_hyp }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account{{ .Values.env_hyp }}
  template:
    metadata:
      labels:
        app: account{{ .Values.env_hyp }}
    spec:
      containers:
      - name: account{{ .Values.env_hyp }}
        image: abhinavmedikonda/account:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgres://abhi:1234@account-db{{ .Values.env_hyp }}:5432/account_db{{ .Values.env_und }}?sslmode=disable"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-db{{ .Values.env_hyp }}
  labels:
    app: account-db{{ .Values.env_hyp }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-db{{ .Values.env_hyp }}
  template:
    metadata:
      labels:
        app: account-db{{ .Values.env_hyp }}
    spec:
      containers:
      - name: account-db{{ .Values.env_hyp }}
        image: abhinavmedikonda/account-db:v1
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "account_db{{ .Values.env_und }}"
        - name: POSTGRES_USER
          value: "abhi"
        - name: POSTGRES_PASSWORD
          value: "1234"
