apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: account-{{ .Values.env }}
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: abhinavmedikonda/oms-account-api:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8081
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        env:
        - name: DB_U
          valueFrom:
            secretKeyRef:
              name: vault
              key: db-username
        - name: DB_P
          valueFrom:
            secretKeyRef:
              name: vault
              key: db-password
        - name: DATABASE_URL
          value: "postgres://$(DB_U):$(DB_P)@db.account-{{ .Values.env }}:5432/account_db_{{ .Values.env }}?sslmode=disable"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: account-{{ .Values.env }}
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: abhinavmedikonda/oms-account-db:v1
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "account_db_{{ .Values.env }}"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: vault
              key: db-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vault
              key: db-password
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: pvc
