apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
spec:
  selector:
    app: account
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: account-db
  labels:
    app: account-db
spec:
  selector:
    app: account-db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432