apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-{{ .Values.env }}
  namespace: order-{{ .Values.env }}
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault
  dataFrom:
  - extract:
      key: order-{{ .Values.env }}
