apiVersion: v1
kind: Service
metadata:
  name: order{{ .Values.env_hyp }}
  labels:
    app: order{{ .Values.env_hyp }}
spec:
  selector:
    app: order{{ .Values.env_hyp }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-db{{ .Values.env_hyp }}
  labels:
    app: order-db{{ .Values.env_hyp }}
spec:
  selector:
    app: order-db{{ .Values.env_hyp }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
